package io.batenzar.revment.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.slf4j.LoggerFactory;

import io.batenzar.revment.manager.RecordManager;
import io.batenzar.revment.model.Record;

import static org.junit.Assert.*;

import java.util.List;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	RecordManager recordManager = new RecordManager();
		Record rec = new Record();
		
		recordManager.addRecord(rec);
		recordManager.addRecord(rec);
		
		List<Record> records = recordManager.getRecords();
		for (Record r : records){
			LoggerFactory.getLogger(LibraryTest.class).info(r.getId());
		}
    }
}
